export const AUTH = {
    LOGIN: 'AUTH_LOGIN',
    LOGOUT: 'AUTH_LOGOUT'
}

export const DASHBOARD = {
    GET_DATA: 'DASHBOARD_GET_DATA',
}

export const ORGANIZATIONS = {
    GET_DATA: 'ORGANIZATIONS_GET_DATA',
}

export const ORGANIZATION_DETAILS = {
    GET_DATA: 'ORGANIZATION_DETAILS_GET_DATA',
}

export const EMPLOYEES = {
    GET_DATA: 'EMPLOYEES_GET_DATA',
}